export const gameData = {
  lol: {
    name: 'League of Legends',
    players: [
      {
        name: 'Kais',
        tag: 'KaisTN',
        avatar: 'https://i.pravatar.cc/150?u=kais',
        role: 'Top Laner',
        rank: 'Challenger',
        lp: '1024 LP',
        team: 'Instinct',
        achievement: 'Tunisian League Winner 2025',
        isPro: true,
        stats: { kda: 4.2, cs_min: 8.9, vision_score: 2.1 },
        main_champions: ['Fiora', 'Aatrox', 'Gwen'],
        match_history: [
          { champion: 'Fiora', result: 'Victory', kda: '10/2/5' },
          { champion: 'Aatrox', result: 'Defeat', kda: '5/5/3' },
        ],
      },
      {
        name: 'Zizou',
        tag: 'zizou',
        avatar: 'https://i.pravatar.cc/150?u=zizou',
        role: 'Mid Laner',
        rank: 'Grandmaster',
        lp: '550 LP',
        team: 'No Org',
        achievement: 'Rank 1 EUW for 2 weeks',
        isPro: false,
        stats: { kda: 5.1, cs_min: 9.5, vision_score: 1.8 },
        main_champions: ['LeBlanc', 'Syndra', 'Akali'],
        match_history: [
            { champion: 'LeBlanc', result: 'Victory', kda: '12/1/8' },
            { champion: 'Syndra', result: 'Victory', kda: '9/3/11' },
        ],
      },
    ],
    stats: [
      { key: 'kda', label: 'KDA Ratio' },
      { key: 'cs_min', label: 'CS per Minute' },
      { key: 'vision_score', label: 'Vision Score/Game' },
    ],
  },
  valorant: {
    name: 'Valorant',
    players: [
      {
        name: 'Amine',
        tag: 'Ninjax',
        avatar: 'https://i.pravatar.cc/150?u=amine',
        role: 'Duelist',
        rank: 'Radiant',
        team: 'Falcons',
        achievement: 'MENA Champion 2025',
        isPro: true,
        stats: { hs_percent: 28, acs: 280, adr: 180 },
        main_agents: ['Jett', 'Raze', 'Reyna'],
        match_history: [
          { agent: 'Jett', result: 'Victory', score: '25/10/5' },
          { agent: 'Raze', result: 'Victory', score: '22/15/8' },
        ],
      },
      {
        name: 'Khalil',
        tag: 'khalil',
        avatar: 'https://i.pravatar.cc/150?u=khalil',
        role: 'Controller',
        rank: 'Immortal 3',
        team: 'GEKOLOR',
        achievement: 'VCL France Finalist',
        isPro: true,
        stats: { hs_percent: 22, acs: 210, adr: 140 },
        main_agents: ['Omen', 'Viper', 'Astra'],
        match_history: [
            { agent: 'Omen', result: 'Defeat', score: '15/18/10' },
            { agent: 'Viper', result: 'Victory', score: '18/12/12' },
        ],
      },
    ],
    stats: [
      { key: 'hs_percent', label: 'Headshot %' },
      { key: 'acs', label: 'Avg. Combat Score' },
      { key: 'adr', label: 'Avg. Damage/Round' },
    ],
  },
  csgo: {
    name: 'CS2',
    players: [
      {
        name: 'Yassine',
        tag: 'smokey',
        avatar: 'https://i.pravatar.cc/150?u=yassine',
        role: 'AWPer',
        rank: 'Global Elite',
        elo: '3500',
        team: 'Team Ooredoo',
        achievement: 'IESF World Champion 2024',
        isPro: true,
        stats: { kd: 1.4, adr: 92.5, hs_percent: 45 },
        main_weapons: ['AWP', 'AK-47', 'Deagle'],
        match_history: [
          { map: 'Mirage', result: 'Victory', score: '28-12' },
          { map: 'Inferno', result: 'Victory', score: '22-10' },
        ],
      },
      {
        name: 'Mehdi',
        tag: 'Styko',
        avatar: 'https://i.pravatar.cc/150?u=mehdi',
        role: 'Rifler',
        rank: 'Faceit Lvl 10',
        elo: '3200',
        team: 'No Org',
        achievement: 'EPL Qualifier',
        isPro: false,
        stats: { kd: 1.2, adr: 85.1, hs_percent: 55 },
        main_weapons: ['AK-47', 'M4A4', 'USP-S'],
        match_history: [
          { map: 'Nuke', result: 'Defeat', score: '18-20' },
          { map: 'Ancient', result: 'Victory', score: '25-15' },
        ],
      },
    ],
    stats: [
      { key: 'kd', label: 'K/D Ratio' },
      { key: 'adr', label: 'Avg. Damage/Round' },
      { key: 'hs_percent', label: 'Headshot %' },
    ],
  },
};

export const gameThemes = {
  'League of Legends': {
    'bg-primary': '#0B0F14',
    'bg-secondary': '#121821',
    'bg-tertiary': '#1A2330',
    'border-subtle': '#232E3E',
    'border-strong': '#2F3B52',
    'text-primary': '#E6EDF3',
    'text-secondary': '#9FB0C3',
    'text-muted': '#6B7C93',
    'accent-primary': '#C8AA6E',
    'accent-secondary': '#0A1428',
    'accent-text': '#0B0F14',
    glow: 'shadow-[0_0_15px_rgba(200,170,110,0.25)]',
  },
  Valorant: {
    'bg-primary': '#0F1923',
    'bg-secondary': '#1a242e',
    'bg-tertiary': '#242f3b',
    'border-subtle': '#313a44',
    'border-strong': '#454e5a',
    'text-primary': '#ECE8E1',
    'text-secondary': '#a2a6a8',
    'text-muted': '#768079',
    'accent-primary': '#FF4655',
    'accent-secondary': '#0F1923',
    'accent-text': '#FFFFFF',
    glow: 'shadow-[0_0_15px_rgba(255,70,85,0.25)]',
  },
  CS2: {
    'bg-primary': '#1A1A1A',
    'bg-secondary': '#242424',
    'bg-tertiary': '#2e2e2e',
    'border-subtle': '#3a3a3a',
    'border-strong': '#4f4f4f',
    'text-primary': '#E6EDF3',
    'text-secondary': '#b2b2b2',
    'text-muted': '#808080',
    'accent-primary': '#F28C28',
    'accent-secondary': '#1A1A1A',
    'accent-text': '#000000',
    glow: 'shadow-[0_0_15px_rgba(242,140,40,0.25)]',
  },
};